version: "3.9"

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      TACO_ENDPOINT: https://openai-tw.com/toao/
      FETCH_INTERVAL_HOURS: '4'
    ports:
      - 8000:8000
    networks:
      - taco-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://backend:8000
    ports:
      - 3000:3000
    networks:
      - taco-network

networks:
  taco-network:
    driver: bridge
